name: 'k3s'
description: 'run kubectl command inside against kubernetes environment'
inputs:
  version:  
    description: 'Version of k3s'
    required: true
    default: 'v1.0.0'
outputs:
  kubeconfig: # id of output
    description: 'Kubeconfig location'
runs:
  using: 'node12'
  main: 'index.js'
